import test from "ava";
import Color from "./Color";

test("Color can be generated from any format", async spec => {
    spec.plan(32);
    const rgbHexColor = new Color("#3264C8");
    spec.is(rgbHexColor.red, 50);
    spec.is(rgbHexColor.green, 100);
    spec.is(rgbHexColor.blue, 200);
    spec.is(rgbHexColor.alpha, 1);
    const rgbFuncColor = new Color("rgb(50,100,200)");
    spec.is(rgbFuncColor.red, 50);
    spec.is(rgbFuncColor.green, 100);
    spec.is(rgbFuncColor.blue, 200);
    spec.is(rgbFuncColor.alpha, 1);
    const rgbaFuncColor = new Color("rgba(50,100,200,.5)");
    spec.is(rgbaFuncColor.red, 50);
    spec.is(rgbaFuncColor.green, 100);
    spec.is(rgbaFuncColor.blue, 200);
    spec.is(rgbaFuncColor.alpha, .5);
    const rgbFuncPercentColor = new Color("rgb(20%,60%,80%)");
    spec.is(rgbFuncPercentColor.red, 51);
    spec.is(rgbFuncPercentColor.green, 153);
    spec.is(rgbFuncPercentColor.blue, 204);
    spec.is(rgbFuncPercentColor.alpha, 1);
    const rgbConstructorColor = new Color(50, 100, 200);
    spec.is(rgbConstructorColor.red, 50);
    spec.is(rgbConstructorColor.green, 100);
    spec.is(rgbConstructorColor.blue, 200);
    spec.is(rgbConstructorColor.alpha, 1);
    const rgbaConstructorColor = new Color(50, 100, 200);
    spec.is(rgbaConstructorColor.red, 50);
    spec.is(rgbaConstructorColor.green, 100);
    spec.is(rgbaConstructorColor.blue, 200);
    spec.is(rgbaConstructorColor.alpha, 1);
    const hslColor = new Color("hsl(220,75%,78%)");
    spec.is(hslColor.red, 50);
    spec.is(hslColor.green, 100);
    spec.is(hslColor.blue, 200);
    spec.is(hslColor.alpha, 1);
    const hslaColor = new Color("hsla(220,75%,78%,.5)");
    spec.is(hslaColor.red, 50);
    spec.is(hslaColor.green, 100);
    spec.is(hslaColor.blue, 200);
    spec.is(hslaColor.alpha, .5);
    const cmykColor = new Color("cmyk(75,50,0,22)");
    spec.is(cmykColor.red, 50);
    spec.is(cmykColor.green, 100);
    spec.is(cmykColor.blue, 200);
    spec.is(cmykColor.alpha, 1);
});